name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
      
    - name: Run tests
      run: |
        go test -p 1 -coverprofile=cover.out ./src/...

    - name: Generate coverage report
      run: |
        go install github.com/axw/gocov/gocov@latest
        go install github.com/AlekSi/gocov-xml@latest
        gocov convert cover.out | gocov-xml > coverage.xml

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml